name: Score Articles Cron

on:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 4 * * *' 
    - cron: '0 10 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  score_articles:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Score Endpoint
        run: |
          curl -X GET "https://quicksnap-ph.vercel.app/api/cron/rankNews" \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}"